### ISSUE TITLE
Cargo.lock file

### ISSUE THREAD

**Issue by 0323pin** [mihaigalos/dusage#3]
What I'd to have is for you to provide a `Cargo.lock` file to avoid a manual step while updating the package.
See for example, `dust` repository,

![2022-01-25-202725_1366x768_scrot](https://user-images.githubusercontent.com/90570748/151046155-bc792655-ee5e-4dcd-b9c9-3f03f1e64ca2.png)

**Comment by 0323pin** [comment]
@mihaigalos package has now been merged into pkgsrc main branch, https://mail-index.netbsd.org/pkgsrc-changes/2022/01/25/msg247615.html

**Comment by mihaigalos** [comment]
I had a look at multiple repos I own, seems the `cargo init` produces only `/target` in `.gitignore`.
If repo is created directly in GitHub with language `Rust`, then `.gitignore` contains:

```toml
# Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
# More information here https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
Cargo.lock
```

I have it locally, let me add it to git.

**Comment by mihaigalos** [comment]
Added in https://github.com/mihaigalos/dusage/commit/5a013f8a8b0995f5314751bf495798e986b8c67b

I'll create a new release once https://github.com/mihaigalos/dusage/issues/4 is fixed.
That one will then contain the `Cargo.lock`.

**Comment by 0323pin** [comment]
Nice, now it's there.
The reason I wanted it is that it's used to generate the following list.

```
CARGO_CRATE_DEPENDS+=  ansi_term-0.12.1
CARGO_CRATE_DEPENDS+=  atty-0.2.14
CARGO_CRATE_DEPENDS+=  autocfg-1.0.1
CARGO_CRATE_DEPENDS+=  bitflags-1.3.2
CARGO_CRATE_DEPENDS+=  byte-unit-4.0.13
CARGO_CRATE_DEPENDS+=  cc-1.0.72
CARGO_CRATE_DEPENDS+=  cfg-if-1.0.0
CARGO_CRATE_DEPENDS+=  clap-2.34.0
CARGO_CRATE_DEPENDS+=  colored-2.0.0
CARGO_CRATE_DEPENDS+=  hermit-abi-0.1.19
CARGO_CRATE_DEPENDS+=  lazy_static-1.4.0
CARGO_CRATE_DEPENDS+=  libc-0.2.114
CARGO_CRATE_DEPENDS+=  memoffset-0.6.5
CARGO_CRATE_DEPENDS+=  nix-0.23.1
CARGO_CRATE_DEPENDS+=  strsim-0.8.0
CARGO_CRATE_DEPENDS+=  textwrap-0.11.0
CARGO_CRATE_DEPENDS+=  unicode-width-0.1.9
CARGO_CRATE_DEPENDS+=  utf8-width-0.1.5
CARGO_CRATE_DEPENDS+=  vec_map-0.8.2
CARGO_CRATE_DEPENDS+=  winapi-0.3.9
CARGO_CRATE_DEPENDS+=  winapi-i686-pc-windows-gnu-0.4.0
CARGO_CRATE_DEPENDS+=  winapi-x86_64-pc-windows-gnu-0.4.0
```

When it's not there, I need to first generate it and then convert it into the above using `sed` and some manual editing.

Feel free to close this issue.
I'll make PR with install instructions tomorrow.

**Comment by mihaigalos** [comment]
Ok. I'm tagging and releasing `0.2.1`.

**Comment by 0323pin** [comment]
Thanks!
I'll probably won't be able to push an update tonight.
Will see what I can do.
